class Callback:
    def __init__(self):
        self.errored: bool = False
        
    def on_some_info(self, msg): ...
    def on_some_warn(self, msg): ...
    def on_some_success(self, msg): ...
    def on_some_error(self, msg): ...
    def on_unknow_error(self, msg): ...
